### PR TITLE
build: bump node to v20

### PR DESCRIPTION
**Pull request by martinm82**
Fixes the deprecation warning:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: batista/lint-filenames@1b766f13475cbdd2df8f2b75d8afda9a48ce7d84. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

### CODE REVIEW

**Comment by martinm82** [comment]
@batista any chance you could review this PR?

**Comment by batista** [comment]
@martinm82 thanks for the ping! I haven't been watching this repo closely for a while, I'm reviewing it now.

**Comment by martinm82** [comment]
@batista thanks a lot. Any chance you could release a new version of the action?

**Comment by batista** [comment]
@martinm82 just did a `v2.0.0` release, let me know if you run into issues :)

**Pull request merged**
